//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobil
{
    using System;
    using System.Collections.Generic;
    
    public partial class cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cars()
        {
            this.order_car = new HashSet<order_car>();
        }
    
        public int id_mobil { get; set; }
        public string nama { get; set; }
        public string vendor { get; set; }
        public Nullable<decimal> harga_sewa { get; set; }
        public string transmisi { get; set; }
        public string bagasi { get; set; }
        public string deskripsi { get; set; }
        public byte[] image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_car> order_car { get; set; }
    }
}
