//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobil
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_car
    {
        public int id_order_car { get; set; }
        public Nullable<int> id_order { get; set; }
        public Nullable<int> id_car { get; set; }
        public Nullable<int> jumlah { get; set; }
        public Nullable<System.DateTime> waktu_ambil { get; set; }
        public Nullable<System.DateTime> waktu_kembali { get; set; }
    
        public virtual cars cars { get; set; }
        public virtual orders orders { get; set; }
    }
}
