//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobil
{
    using System;
    using System.Collections.Generic;
    
    public partial class payments
    {
        public Nullable<int> id_admin { get; set; }
        public int id_payment { get; set; }
        public Nullable<int> id_member { get; set; }
        public Nullable<int> id_order { get; set; }
        public Nullable<System.DateTime> waktu_bayar { get; set; }
        public string nama_rekening { get; set; }
        public Nullable<decimal> nominal { get; set; }
        public string nama_bank { get; set; }
        public string nomor_rekening { get; set; }
        public Nullable<decimal> denda { get; set; }
    
        public virtual admins admins { get; set; }
        public virtual orders orders { get; set; }
    }
}
