//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobil
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_for_payments
    {
        public int id_order_car { get; set; }
        public string nama { get; set; }
        public int id_order { get; set; }
        public int id_member { get; set; }
        public string nama_admin { get; set; }
        public Nullable<System.DateTime> waktu_ambil { get; set; }
        public Nullable<System.DateTime> waktu_kembali { get; set; }
        public string nama_member { get; set; }
        public string status { get; set; }
        public string invoice_number { get; set; }
        public Nullable<System.DateTime> tgl_order { get; set; }
        public Nullable<decimal> harga_sewa { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public int id_payment { get; set; }
    }
}
