//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobil
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_cars_ready_for_order
    {
        public string nama { get; set; }
        public string vendor { get; set; }
        public Nullable<decimal> harga_sewa { get; set; }
        public byte[] image { get; set; }
        public string transmisi { get; set; }
        public string bagasi { get; set; }
        public string deskripsi { get; set; }
        public string status { get; set; }
        public int id_mobil { get; set; }
        public Nullable<int> id_member { get; set; }
        public Nullable<System.DateTime> waktu_ambil { get; set; }
        public Nullable<System.DateTime> waktu_kembali { get; set; }
        public Nullable<int> jumlah { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<int> Expr1 { get; set; }
    }
}
